### ISSUE TITLE
get_class() expects parameter 1 to be object, array given getting this error while trying to insert data in product table 

### ISSUE THREAD

**Issue by dsv4890** [Algo-Web/POData-Laravel#173]

**Comment by c-harris** [comment]
What were you using for a client?

**Comment by dsv4890** [comment]
I'm sending data using post request as array. Is there any particular format in which we have to pass data for insert

**Comment by c-harris** [comment]
Are you using XML or json? Because Json is untested. Would you be open to modifying the podata error handler to get a stack trace? Also is it possible you could provide a sanatised copy of the submitted data?

**Comment by CyberiaResurrection** [comment]
@dsv4890 , what data are you trying to post, and to which route?  That looks suspiciously like the tail end of an error message.

Are you running against dev-master or 0.3.* of POData-Laravel?

**Comment by dsv4890** [comment]
I am posting on route http://127.0.0.1:8000/odata.svc/Products using Post method 
@c-harris i am sending data in JSON format

**Comment by c-harris** [comment]
@CyberiaResurrection we should probably get cracking on json testing and checking.

@dsv4890 give us a little bit to track this one down

**Comment by dsv4890** [comment]
ok

**Comment by dsv4890** [comment]
@CyberiaResurrection I am running both dev-master and 0.3.*  in separate projects but not getting any solution how to post data for crud operation using this package

**Comment by CyberiaResurrection** [comment]
@dsv4890 , thanks for the reply.  I strongly suspect the cause (see @c-harris comment above), but if you can, could you try submitting your post request in atom format, rather than json?

**Comment by dsv4890** [comment]
I have tried to send the response in atom formate and I'm getting an error 
The array type must be specified as "array<K, V>" for Key-Value-Pairs.

**Comment by CyberiaResurrection** [comment]
@dsv4890 , thanks for trying that.  What client are you using to send the requests?

**Comment by dsv4890** [comment]
postman

**Comment by dsv4890** [comment]
Can you please provide any kind of example or sample data for post request!

**Comment by CyberiaResurrection** [comment]
It looks like you might have tripped over a difference in JMS serialiser versions - to check, you're running minimum-stability: dev on both your test projects?

I've pushed a fix to the odata-metadata project - can you please composer update and see what pain persists?

**Comment by dsv4890** [comment]
ok

**Comment by dsv4890** [comment]
I have run composer update command but still getting the same error 
It would be good if you can send me demo data so i can verify I'm inserting data in proper format

**Comment by CyberiaResurrection** [comment]
OK, here's the best I can find on line (from the OData v3 dox - http://www.odata.org/documentation/odata-version-3-0/atom-format/ , section 6.1) for atom format:

```
<entry>
  <id>http://services.odata.org/OData/OData.svc/Products(0)</id> 
  <title /> 
  <summary /> 
  <updated>2012-03-30T07:11:05Z</updated> 
  <author>
    <name /> 
  </author>
  <link rel="edit" title="Product" href="Products(0)" /> 
  <link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/Category" type="application/atom+xml;type=entry" title="Category" href="Products(0)/Category" /> 
  <link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/Supplier" type="application/atom+xml;type=entry" title="Supplier" href="Products(0)/Supplier" /> 
  <category term="ODataDemo.Product" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" /> 
  <content type="application/xml">
    <metadata:properties>
      <data:ID m:type="Edm.Int32">0</data:ID> 
      <data:Name>Bread</data:Name>
      <data:Description>Whole grain bread</data:Description>
      <data:ReleaseDate metadata:type="Edm.DateTime">1992-01-01T00:00:00</data:ReleaseDate> 
      <data:DiscontinuedDate metadata:type="Edm.DateTime" metadata:null="true" /> 
      <data:Rating metadata:type="Edm.Int32">4</data:Rating> 
      <data:Price metadata:type="Edm.Decimal">2.5</data:Price> 
    </metadata:properties>
  </content>
</entry>
```

**Comment by dsv4890** [comment]
sending data in the same format i'm getting following error 
assert (): Property content must be instanceof ODataPropertyContent. failed

when i'm trying to use this in 0.3.* project i'm getting following error 
Call to a member function getValue() on null
at vendor\algo-web\o-data-metadata\src\MetadataManager.php

**Comment by dsv4890** [comment]
Is crud operation not possible using this package?
Can I please get an update about POST method URL...

**Comment by dsv4890** [comment]
Hi 
I'm waiting for a response on my issue about POST request
 error  get_class() expects parameter 1 to be object, array given

**Comment by c-harris** [comment]
@dsv4890 I am very sorry this has taken so long to resolve. sadly my own life kind of bulldozed my open source commitments of late. I underwent treatment for cancer this year and the ongoing side effects have been greatly slowing down all my development work. however, I am investigating your issue today. please expect a reply in the next 7 days (upper bound, could be sooner) with a solution.

**Comment by dsv4890** [comment]
ok Thank you
